create table tb_guest (id int8 generated by default as identity, name varchar(255), qty_companion int4, primary key (id));
INSERT INTO tb_guest (name, qty_companion) VALUES ('John', 2);
INSERT INTO tb_guest (name, qty_companion) VALUES ('Daneris', 3);
INSERT INTO tb_guest (name, qty_companion) VALUES ('Tyrion', 1);
